# Generated by Django 5.0.2 on 2024-02-17 09:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageItemInfo',
            fields=[
                ('message_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=35)),
                ('text', models.TextField()),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('username', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MessageReceivers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.BooleanField(default=False)),
                ('message_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Messages.messageiteminfo')),
                ('receiver', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, to='Messages.users')),
            ],
        ),
        migrations.AddField(
            model_name='messageiteminfo',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Messages.users'),
        ),
        migrations.AddConstraint(
            model_name='messagereceivers',
            constraint=models.UniqueConstraint(fields=('message_id', 'receiver'), name='unique_migration_host_combination_message_receiver'),
        ),
        migrations.AddConstraint(
            model_name='messageiteminfo',
            constraint=models.UniqueConstraint(fields=('message_id', 'sender'), name='unique_migration_host_combination_message_sender'),
        ),
    ]
