# Generated by Django 5.0.2 on 2024-02-17 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagereceivers',
            name='receiver',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='receivers', to='Messages.users'),
        ),
    ]
